// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAZ8n0EcNEvRRA2Rod-Shl9byfk3St18',
    appId: '1:947589126171:android:ac9ec6f95a7718a25300be',
    messagingSenderId: '947589126171',
    projectId: 'my-pics-be49d',
    storageBucket: 'my-pics-be49d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrlocDNrSnsvU67pzfFTFkWn9mR8aXUC8',
    appId: '1:947589126171:ios:4c36d841259b95d45300be',
    messagingSenderId: '947589126171',
    projectId: 'my-pics-be49d',
    storageBucket: 'my-pics-be49d.appspot.com',
    androidClientId:
        '947589126171-r23btemd02nhranb73rhfsbupho6up8p.apps.googleusercontent.com',
    iosClientId:
        '947589126171-rm3j8rmkc9gv0klre2g04l5s96rasflr.apps.googleusercontent.com',
    iosBundleId: 'com.prostreet1212.myPics',
  );
}
